# For help please refer to the bukkit dev page: https://dev.bukkit.org/projects/pickuparrows
usePermissions: false
pickupFrom:
  skeleton:
    fire: true
    normal: true
    spectral: true
    tipped: true
    trident: true
  player:
    fire: true
    normal: true
    spectral: true
    tipped: true
    trident: true
    crossbow:
      fire: true
      normal: true
      spectral: true
      tipped: true
      multishot:
        fire: false
        normal: false
        spectral: false
        tipped: false
  dispenser:
    fire: true
    normal: true
    spectral: true
    tipped: true
    trident: true
  drowned:
    fire: true
    normal: true
    spectral: true
    tipped: true
    trident: true
  pillager:
    fire: true
    normal: true
    spectral: true
    tipped: true
    trident: true
  unknown:
    fire: false
    normal: false
    spectral: false
    tipped: false
    trident: false
ignoreCreativeArrows: false
useWorldGuard: false
useListAsBlacklist: false
regions: []
