_job_base: &job_base
  working_directory: ~/pickup-arrows
  steps:
    - checkout
    - run: java -version
    - run: mvn -version
    - restore_cache:
        key: pickup-arrows-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
          - ~/.m2
        key: pickup-arrows-{{ checksum "pom.xml" }}
    - run: mvn clean test

version: 2
jobs:
  jdk8:
    <<: *job_base
    docker:
      - image: maven:3-jdk-8-slim
  jdk11:
    <<: *job_base
    docker:
      - image: maven:3-jdk-11-slim
workflows:
  version: 2
  all_jdks:
    jobs:
      - jdk8
      - jdk11
